---
name: Test

on: [push]

jobs:
 build:
   runs-on: ubuntu-latest
  
   steps:
   - name: Fetch Access Token from Artifactory
     id: fetch_access_token
     env:
       ID_TOKEN: ${{ steps.idtoken.outputs.id_token }}
     run: |
       ACCESS_TOKEN=$(curl \
       -X POST \
       -H "Content-type: application/json" \
       https://sarangeplus.jfrog.io/access/api/v1/oidc/token \
       -d \
       "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"$ID_TOKEN\", \"provider_name\": \"github-oidc-integration\"}" | jq .access_token | tr -d '"')
       echo ACCESS_TOKEN=$ACCESS_TOKEN >> $GITHUB_OUTPUT

   - name: Get ID Token (cURL method)
     id: idtoken
     run: |
       ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
       "${ACTIONS_ID_TOKEN_REQUEST_URL}" | jq .value | tr -d '"')
       echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_OUTPUT
          
   # This action checks out the code from the repository
   - name: Checkout Code     
     uses: actions/checkout@v2

   # This action sets up the JFrog CLI with the Artifactory URL and access token     
   - uses: jfrog/setup-jfrog-cli@v3 
     env:
    # JFrog platform url (for example: https://acme.jfrog.io) 
      JF_URL: ${{ secrets.JF_URL }}
      
      # Basic authentication credentials
      JF_USER: ${{ secrets.JF_USER }}
      JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

   - run: |
       jf rt ping

       
